version: '2'
services:
    jhvita-app:
        image: jhvita
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhvita-mysql:3306/jhvita?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=jhvita-elasticsearch:9300
        ports:
            - 8080:8080
    jhvita-mysql:
        extends:
            file: mysql.yml
            service: jhvita-mysql
    jhvita-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: jhvita-elasticsearch
